# NOTE versions will be retained on the app server, and previous
# versions can be restored via the administrative console.
application: helloworld 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.app

libraries:
- name: jinja2
  version: 2.6


